### ISSUE TITLE
Package FFcast for distributions

### ISSUE THREAD

**Issue by ropery** [ropery/FFcast#21]
Request inclusion of both ffcast & xrectsel in popular distros.
When asked what this is for, just say FFcast is primarily used for screen capture & recording ;)

Point the maintainers to the Arch Linux packages for a start,
https://aur.archlinux.org/packages/ffcast
https://aur.archlinux.org/packages/xrectsel
- [x] Arch Linux
- [ ] [Debian](https://packages.debian.org/search?keywords=ffcast&searchon=names&suite=all&section=all): send [Request For Package](https://wiki.debian.org/RFP).
- [ ] Fedora
- [x] [Gentoo](https://packages.gentoo.org/packages/search?q=ffcast)
- [ ] [Mageia](http://madb.mageia.org/package/list/t_search/ffcast/application/0): send [Package Request](https://wiki.mageia.org/en/How_to_report_a_bug_properly#How_to_file_a_package_request).
- [x] [NixOS](https://nixos.org/nixos/packages.html)
- [x] [openSUSE](https://software.opensuse.org/package/ffcast)

**Comment by guyonvarch** [comment]
Hi, ffcast and xrectsel will be available soon on NixOS : 
https://github.com/NixOS/nixpkgs/pull/21141
https://github.com/NixOS/nixpkgs/pull/21153

**Comment by lolilolicon** [comment]
Very good @guyonvarch, thanks!

**Comment by aeliton** [comment]
Hi, I just sent an Intent to Package FFcast for debian. Thank you for publishing such great tool!

**Comment by siduck76** [comment]
pkg for void linux :(

**Comment by ropery** [comment]
Closing this issue.
Any distro should find it easy to package this by referring to the Archlinux/AUR package source.
Though but few have packaged this: <https://repology.org/project/ffcast/versions>
[![Packaging status](https://repology.org/badge/vertical-allrepos/ffcast.svg)](https://repology.org/project/ffcast/versions)
